### ISSUE TITLE
Parse H.264 stream failed

### ISSUE THREAD

**Issue by Unicowoco** [ChihChengYang/wfs.js#11]
Hi,
   I got a problem with wfs.js that it seems works not good when the system of PC is windows 7. Because the stream works very well when the system is windows 10, however, nothing shows with windows 7. And I got a log 'trying to append although a media error occured, flush segment and abort', already test on 2 PC with windows 10 and 3 PC with windows 7, the results were what I said before. Can you tell me what's the problem? Or if I want to solve it, what's the solution, thank you so much!

**Comment by ChihChengYang** [comment]
I just tried on Linux (ubuntu) and Windows 10. I think that would be important running on the same version of browser.

**Comment by Unicowoco** [comment]
Thanks for your response, the problem is I can't guarantee users use the same version. Btw, I tried to play a mp4 file instead of stream in window 7, it works well. I think this means the part of parse should be ok, so should I need to add some code to deal with stream?

**Comment by Unicowoco** [comment]
What a pity, thanks for your help.
