### ISSUE TITLE
能不能把websocket模块提取出来

### ISSUE THREAD

**Issue by chenchenwuai** [ChihChengYang/wfs.js#18]
websocket模块是否能够提取出来，我的项目中需要自己打开websocket，然后处理每次接收到的数据后，才能得到真实的数据。

**Comment by kinpol** [comment]
https://github.com/kinpol/singleWfsjs

**Comment by kinpol** [comment]
> websocket模块是否能够提取出来，我的项目中需要自己打开websocket，然后处理每次接收到的数据后，才能得到真实的数据。

当前的版本有些问题,我把编译好之前的版本放在目录下了.那个版本是ok的.https://github.com/kinpol/singleWfsjs/blob/master/wfs.js

**Comment by chenchenwuai** [comment]
我发现了一个新的repo [jmuxer](https://github.com/samirkumardas/jmuxer)，感兴趣的小伙伴可以试一试
