### ISSUE TITLE
video丢帧和渲染控制问题

### ISSUE THREAD

**Issue by kinpol** [ChihChengYang/wfs.js#19]
发现video标签有丢帧现象,而且能不能知道那一帧渲染或者没有渲染?

**Comment by MingoJiang** [comment]
调试状态下一步一步跟进去看一下，应该能找到的。

**Comment by MingoJiang** [comment]
请求个问题， 音频怎么同步播放？

**Comment by kinpol** [comment]
已经找到了，有参数可以导出。音频我们现在没有处理，可能帮不了你。

**Comment by Yordroid** [comment]
> 已经找到了，有参数可以导出。音频我们现在没有处理，可能帮不了你。

我这边子码流会丢帧，主的不会，是哪里的问题呢？麻烦指导一下，谢谢

**Comment by kinpol** [comment]
用码流分析工具，看看保存下来的子码流是不是有丢帧现象。

**Comment by kinpol** [comment]
> > 已经找到了，有参数可以导出。音频我们现在没有处理，可能帮不了你。
> 
> 我这边子码流会丢帧，主的不会，是哪里的问题呢？麻烦指导一下，谢谢

用码流分析工具，看看保存下来的子码流是不是有丢帧现象。
