### ISSUE TITLE
Websocket streaming NAL Units

### ISSUE THREAD

**Issue by AmdEagle** [ChihChengYang/wfs.js#2]
HI i already have a websocket setup with outputs NAL Units how i use the wfs to play the stream on browser ?

`let wfs = new Wfs();`
`function onStreamDataReceived( nal )`
`{`
    `//.....how do i pass the nal i receive to you wfs obj ??`
`}` 

Please help

**Comment by ChihChengYang** [comment]
https://github.com/ChihChengYang/wfs.js/blob/master/demo/index.html
            var video1 = document.getElementById("video1"),
            wfs = new Wfs();    
            wfs.attachMedia(video1,'ch1'); 

<===This will create mediaSource buffer and one websocket with "channel name" (ch1,here) connect to server ...

https://github.com/ChihChengYang/wfs.js/blob/master/src/controller/flow-controller.js
      var client = new WebSocket( 'ws://' + window.location.host + '/' +  data.websocketName );
      this.wfs.attachWebsocket(client,data.channelName);
<=== You can change your server's IP here. Once server receive client's connection that will start to send data matching "channel name". You may check out https://github.com/ChihChengYang/wfs.js/blob/master/server/wfs_server_lite.go
 
https://github.com/ChihChengYang/wfs.js/blob/master/src/loader/websocket-loader.js
<== You may check this if you would like to process NAL data...

**Comment by ChihChengYang** [comment]
First, You need to modify codes to escape from default websockt connection. 
Once you receive the nal packets using this.wfs.trigger(Event.H264_DATA_PARSING, {data: copy }); to trigger h.264 parser that will demux h.264 into fmp4.

**Comment by AmdEagle** [comment]
Would be able to create a js file which does not connect to websocket. where i can choose to input stream to be muxed. I tried to change you code but didnt have in any luck in getting to work.

It would be great help to me
