### ISSUE TITLE
下载下来项目 为什么运行不了

### ISSUE THREAD

**Issue by weichenzhiyi** [ChihChengYang/wfs.js#26]
执行了
wfs.js
setup node.js/npm dev environement
cd wfs.js
npm install
npm run build
然后用vcode形成一个liveServer 打开demo的index.html页 一直在转圈。
操作步骤哪里出错了？
我看写的readme.md里
run ./demo/wfs_server
我在demo下没找到这个wfs.server呢

**Comment by ChihChengYang** [comment]
demo server

1.Setup go's dev environement

2. go get "github.com/gorilla/websocket"

3. go get "github.com/satori/go.uuid"

4. ./server/build_lite.sh
