### ISSUE TITLE
你好，播放到最后一帧，能否进行等待，而不是又从头开始播 ？

### ISSUE THREAD

**Issue by caipy0904** [ChihChengYang/wfs.js#28]

**Comment by cui-daniel** [comment]
相同的问题，你的解决了吗

**Comment by caipy0904** [comment]
> 相同的问题，你的解决了吗

我是把onSBUpdateEnd 方法里 this.mediaSource.endOfStream(); 和 that.media.play();这两行注释了，你可以试试~

**Comment by cui-daniel** [comment]
是可以的，非常感谢
