### ISSUE TITLE
不能调用wfs.js内部函数&实时播放缓存问题

### ISSUE THREAD

**Issue by lanye233** [ChihChengYang/wfs.js#31]
**一、不能调用wfs.js内部函数=>无法控制websocket何时连接**
我的项目是由Vue编写的，之前自己写过一个websocket（要接受除视频以外的其他实时数据），由于wfs.js中也有一个websocket，所以想把两个整合起来，但是尝试了多种方法都不行。其中一种方法是尝试调用wfs.js中的`send()`方法，但无法调用。我想知道下面代码中的`new Wfs()`是wfs.js代码中的`var Wfs = function()...`吗？如果是，为什么它认识`Wfs()`却不认识`WebsocketLoader()`？有什么办法可以调用wfs.js中的websocket相关函数吗？

```
window.onload = function() {
            if (Wfs.isSupported()) {
                var video1 = document.getElementById("video1"),
                    wfs = new Wfs();
                //var websocketLoader = new WebsocketLoader();
               //报错：WebsocketLoader未定义
                wfs.attachMedia(video1, 'ch1');
                 //websocketLoader .onWebsocketMessageSending();
            }
        };
```

**2.实时播放缓存问题**
我的应用是单页面应用，其中点击出现小窗口，视频页面是要经过至少两个点击操作才能出现的。根据我查到的资料得知，wfs.js里的函数是 **立即执行函数（匿名函数）** 的写法，因此一打开网页就会连接websocket，并且收到视频数据。因此等我打开视频页面时，已经有20-30s的缓存，这不符合实时性的要求。我尝试过去掉 `window.onload = function()...` ，或者修改配置为多页面应用，都未能成功解决。
请问有什么办法可以解决吗？

**Comment by sergey-suzdaltsev** [comment]
1. WebSocket is created in method onMediaAttached of class FlowController. You can make it public and use its methods outside.
2. You can clean the media cache with  [MSE API](https://developer.mozilla.org/en-US/docs/Web/API/SourceBuffer/remove). However, you need to control the correctness of the interval (start, end).
In your case, it is easier to open the player window separately modal and enable auto play.

**Comment by lanye233** [comment]
> 
> 
>     1. WebSocket is created in method onMediaAttached of class FlowController. You can make it public and use its methods outside.
> 
>     2. You can clean the media cache with  [MSE API](https://developer.mozilla.org/en-US/docs/Web/API/SourceBuffer/remove). However, you need to control the correctness of the interval (start, end).
>        In your case, it is easier to open the player window separately modal and enable auto play.

@sergey-suzdaltsev 
 谢谢你的回答。
第二个视频缓存的问题我已经解决了，通过注释onSBUpdateEnd 方法里的`this.mediaSource.endOfStream()` 和 `that.media.play()`这两行，然后在video标签里加上autoplay，去掉controls。
第一个调用websocket方法的问题我还没有解决。
因为wfs.js中的代码全部写在了一个大的闭包函数中（我不确定我的判断是否正确，可能也是匿名函数），它是立即执行的，在页面创建时就会连接websocket接受视频数据。
```
(function(f)){...
})(function() {...
});

```
但我的项目还需要断开重连的操作（有多个不同的视频数据），所以需要能够调用**websocket中的初始化方法、发送数据方法和关闭websocket方法。**
我理解你所说的将它变为公开然后调用，但我水平有限，我不知道该如何改写wfs.js里的代码，是将FlowController整个挪到外面吗？我曾经尝试将wfs.js和我自己写的websocket合并，但这行不通，它无法辨认合并后的wfs.js内容。我也尝试直接将onMediaAttached中的new websocket直接调用我自己写的websocket，虽然程序没有报错，但这样改写它就无法执行与websocket相关的方法了，所以也不可行。

**Comment by lanye233** [comment]
第一个问题，在CSDN中提问，得到了解答。
[JS如何在外部调用函数内部的函数](https://blog.csdn.net/weixin_43694639/article/details/88723280)

**Comment by lanye233** [comment]
> 我发现注释onSBUpdateEnd 方法里的this.mediaSource.endOfStream() 和 that.media.play()这两行并不是我以为的解决了缓存问题。

MediaSource 接口的 endOfStream() 方法意味着流的结束。

```
key: 'onSBUpdateEnd',
value: function onSBUpdateEnd(event) {
// Firefox
          if (this.browserType === 1) {
                  //this.mediaSource.endOfStream(); 
                  //this.media.play();
          }
          this.appending = false;
          this.doAppending();
          this.updateMediaElementDuration();
}       
```

> 注释掉这两行，只是让视频流永远不结束，所以视频控件上总时间是13多个小时，而当前时间总是在开始部分。这样会导致视频有卡顿的现象。

> 保留这两行，就是当没有新的流过来的时候，判断流已结束，并且开始从头播放。   
这样会出现刚开始时，播放1-2s就从头播放，如果在中间播放过程中播到尾巴了（判断没有新的流了），不是暂停而是又重新开始播放。这样就一点都不实时了。   
（以上都是猜测……）

---

**现在想解决要么卡顿要么不实时的两难问题。**

1. 可能是服务端那边发的不够快
2. 也可能是需要这边做一下缓存处理（但我暂时没找到哪里有缓存的配置）

感觉web端html video这边肯定是有缓存的？但是当我点击其他时间它得等一会儿才能播放，这不叫缓存吧？头大……
探索中……

**Comment by kinpol** [comment]
把mse拉出来,wfs只留编解码

**Comment by lanye233** [comment]
谢谢 @kinpol
