### ISSUE TITLE
how can i feed h264 raw data by myself?

### ISSUE THREAD

**Issue by hank5000** [ChihChengYang/wfs.js#4]
Hi ChihChengYang,
I use WebRTC to send/receive the h264 raw data, how can i feed received h264 raw data to wfs.js?

**Comment by ChihChengYang** [comment]
This project creates a Go server (wfs_server_lite.go) to send WebSocket data and uses a h.264 raw file as demo. You could check out "app264Streaming()"....   
wfs.js client <---> WebSocket  <---> Go server

**Comment by hank5000** [comment]
Hi ChihChengYang, can i contact you directly? are you Chinese?

**Comment by ChihChengYang** [comment]
Yeah, You could leave your email. I will contact you by that later today...

**Comment by hank5000** [comment]
OK,
Email: hankwuwu@gmail.com 
Thanks 👍
