### ISSUE TITLE
Regarding streaming server

### ISSUE THREAD

**Issue by samirkumardas** [ChihChengYang/wfs.js#5]
Hi,

It may be silly question but why do you need yyyyyyy.txt file for serving stream over web socket?
Also how did you generate that (yyyyyyy.txt) file?  Is it not possible sending byte stream on the fly instead of reading chunk size from txt file?

Thanks
Samir

**Comment by ChihChengYang** [comment]
Hi,
 yyyyyyy.txt file just uses for checking and demo how server works and actually does not need that. I captured and saved size of NAL-unit in yyyyyyy.txt file from h.264 streaming, so that's ok to use h.264 streaming directly.

**Comment by samirkumardas** [comment]
Hi,

Let me explain what I am trying to do. I have raw h264 file that I get from a http request  and I want to play it.

So my quick plan was to modify `onMediaAttached` in your flow-controller.js and feed response byte array into H264_DATA_PARSING. It was just testing purpose to see either it works or not. I did following:

```
onMediaAttached(data) {  
     /*    
      if (data.websocketName != undefined ){
        var client = new WebSocket( 'ws://' + window.location.host + '/' +  data.websocketName );
        this.wfs.attachWebsocket(client,data.channelName);
      }else{
         console.log('websocketName ERROE!!!');
     } */

    var url = 'panda_annexb.h264';

    var xhr = new XMLHttpRequest;
    xhr.open('get', url);
    xhr.responseType = 'arraybuffer';
    xhr.onload = function () {
       var data = new Uint8Array(xhr.response);
       this.wfs.trigger(Event.H264_DATA_PARSING, {data: data });
    }.bind(this);
    xhr.send();
  }
```

But it plays only first frame and got stuck. What could the reason?  
According to debug, It extracts all NAL units correctly and fed into MES after muxing.

**Comment by ChihChengYang** [comment]
Hi Samir,
 "this.wfs.trigger(Event.H264_DATA_PARSING, {data: data });" that needs to feed NAL-unit chunk data one by one. I have no idea about XMLHttpRequest. Maybe that will need to process Uint8Array as NAL-unit chunk data.

**Comment by samirkumardas** [comment]
Thank you, let me try.
