### ISSUE TITLE
Could you let me know how to debug dist/wfs.js?

### ISSUE THREAD

**Issue by h4hero** [ChihChengYang/wfs.js#6]
Yeah. it is very basic step, but I couldn't find the way to debug the wfs.js
Im using nodeclipse plugin in eclipse. but I can't figure it out how to debug the code of browserified dist/wfs.js
I hope I can trace it in the files of src/*
Thanks in advance. and I appreciate your code work.

**Comment by ChihChengYang** [comment]
Hi,
I have no idea about nodeclipse. This project just used command line to build and watching status with Chrome DevTools.

**Comment by h4hero** [comment]
Thank you for your reply. OK. I will try to find the way for myself.
BTW I tested h.264 stream playing in chrome. It was no problem. but in firefox the play was not smooth. I think the problem is from the duration time in firefox. I saw the very short duration in firefox video control bar.
 If you have some spare time, Please check the abnormal case. 
I really really want to use your great player.

**Comment by ChihChengYang** [comment]
Yeah,that is a known issue on Firefox. You may also reference this repo. https://github.com/MarkRepo/wfs.js removes the cache buffer to improve delay time.

**Comment by h4hero** [comment]
OK. Let me check it. Have a good day.
